Publish specific xrange version, based on branch
'master' -> xrange@latest
'develop' -> xrange@next

diff --git a/.github/workflows/publish-xrange.yaml b/.github/workflows/publish-xrange.yaml
--- a/.github/workflows/publish-xrange.yaml
+++ b/.github/workflows/publish-xrange.yaml
@@ -33,4 +33,14 @@ jobs:
             exit 1
           fi
 
-          npm view xrange@$dist_tag version # TODO: actually publish
+          published_version=$(npm view xrange@$dist_tag version)
+          incoming_version$(node -pe "require('./package.json').version;")
+
+          if [ $published_version = $incoming_version ]
+          then
+            echo "Cannot publish $published_version again; please, update version by running 'npm version <version>'"
+            exit 1
+          fi
+
+      # finally
+      - run: npm publish
